"""empty message

Revision ID: 07824ca53de8
Revises: 2b6321d7e927
Create Date: 2023-08-08 01:26:25.274168

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07824ca53de8'
down_revision = '2b6321d7e927'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_model', schema=None) as batch_op:
        batch_op.add_column(sa.Column('addedOnDate', sa.DateTime(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_model', schema=None) as batch_op:
        batch_op.drop_column('addedOnDate')

    # ### end Alembic commands ###
