"""empty message

Revision ID: 07e8f72e2c58
Revises: 24e7110588c3
Create Date: 2023-08-08 01:37:22.847876

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07e8f72e2c58'
down_revision = '24e7110588c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_model', schema=None) as batch_op:
        batch_op.add_column(sa.Column('addedOnDate', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_model', schema=None) as batch_op:
        batch_op.drop_column('addedOnDate')

    # ### end Alembic commands ###
