"""empty message

Revision ID: 1ad881c583ed
Revises: 
Create Date: 2023-07-07 11:47:37.640569

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ad881c583ed'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cart_model')
    with op.batch_alter_table('cart', schema=None) as batch_op:
        batch_op.alter_column('userId',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('totalValue',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('product_model', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quantityInCart', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_model', schema=None) as batch_op:
        batch_op.drop_column('quantityInCart')

    with op.batch_alter_table('cart', schema=None) as batch_op:
        batch_op.alter_column('totalValue',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('userId',
               existing_type=sa.INTEGER(),
               nullable=True)

    op.create_table('cart_model',
    sa.Column('cartId', sa.INTEGER(), nullable=False),
    sa.Column('totalValue', sa.INTEGER(), nullable=True),
    sa.Column('products', sa.BLOB(), nullable=True),
    sa.PrimaryKeyConstraint('cartId')
    )
    # ### end Alembic commands ###
