"""empty message

Revision ID: 24e7110588c3
Revises: 5cd9877d7cd8
Create Date: 2023-08-08 01:33:05.584430

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24e7110588c3'
down_revision = '5cd9877d7cd8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_model', schema=None) as batch_op:
        batch_op.add_column(sa.Column('addedOnDate', sa.DateTime(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_model', schema=None) as batch_op:
        batch_op.drop_column('addedOnDate')

    # ### end Alembic commands ###
