"""empty message

Revision ID: 2b6321d7e927
Revises: 8b4178ee16a9
Create Date: 2023-07-11 02:41:11.732789

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b6321d7e927'
down_revision = '8b4178ee16a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ticket_model', schema=None) as batch_op:
        batch_op.add_column(sa.Column('action', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ticket_model', schema=None) as batch_op:
        batch_op.drop_column('action')

    # ### end Alembic commands ###
