"""empty message

Revision ID: 608d803cc99d
Revises: bbc6d6f04439
Create Date: 2023-08-13 15:46:09.520437

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '608d803cc99d'
down_revision = 'bbc6d6f04439'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('order', Models.utilModel.JSONEncodedDict(), nullable=True))
        batch_op.drop_column('orderHistory')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('orderHistory', sa.VARCHAR(), nullable=True))
        batch_op.drop_column('order')

    # ### end Alembic commands ###
