"""empty message

Revision ID: 629425a7da7f
Revises: 16ab11413f40
Create Date: 2023-08-11 00:34:51.289155

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '629425a7da7f'
down_revision = '16ab11413f40'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_order',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('userId', sa.Integer(), nullable=False),
    sa.Column('orderHistory', sa.ARRAY(sa.String()), nullable=True),
    sa.ForeignKeyConstraint(['userId'], ['user_model.uuid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_order')
    # ### end Alembic commands ###
