"""empty message

Revision ID: 84093645e32e
Revises: dd5702bd6824
Create Date: 2023-07-09 23:53:01.861570

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84093645e32e'
down_revision = 'dd5702bd6824'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('section_model',
    sa.Column('sectionId', sa.Integer(), nullable=False),
    sa.Column('sectionKey', sa.String(), nullable=False),
    sa.Column('sectionValue', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('sectionId')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('section_model')
    # ### end Alembic commands ###
