"""empty message

Revision ID: bbc6d6f04439
Revises: 629425a7da7f
Create Date: 2023-08-13 15:14:52.921745

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bbc6d6f04439'
down_revision = '629425a7da7f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_order',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('userId', sa.Integer(), nullable=True),
    sa.Column('orderHistory', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['userId'], ['user_model.uuid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_order')
    # ### end Alembic commands ###
