"""empty message

Revision ID: f7c2b06d62c3
Revises: 608d803cc99d
Create Date: 2023-08-13 15:47:13.469005

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f7c2b06d62c3'
down_revision = '608d803cc99d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('order', Models.utilModel.JSONEncodedDict(), nullable=True))
        batch_op.drop_column('orderHistory')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('orderHistory', sa.VARCHAR(), nullable=True))
        batch_op.drop_column('order')

    # ### end Alembic commands ###
